Create Table if NOT EXISTS cliente(
    ID INTEGER  PRIMARY KEY AUTOINCREMENT, 
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20),
  	EMAIL VARCHAR(50)
);

Create Table if NOT EXISTS carros(
    ID INTEGER   PRIMARY KEY AUTOINCREMENT, 
    modelo VARCHAR(20),
    placa VARCHAR(255) NOT NULL UNIQUE,
  	ano VARCHAR(255) NOT NULL,
  	marca VARCHAR(50)
);

INSERT Into  carros(MODELO, PLACA, ANO, MARCA) VALUES('AUDI Q3','4875JH','2025','AUDI')